import { OPCODES, isaCatalog } from './chimera.js';
const byName=Object.fromEntries(Object.entries(OPCODES).map(([k,v])=>[k.toUpperCase(),v]));
export function parseRegister(s){const m=/^[RZ](\d+)$/i.exec(s.trim());if(!m)throw new SyntaxError(`invalid register ${s}`);const n=Number(m[1]);if(n<0||n>1023)throw new RangeError('register must be 0..1023');return n}
export function parseImmediate(s){const t=s.trim();if(/^[-+]?0x/i.test(t))return BigInt(t);if(/^[-+]?0b/i.test(t))return BigInt(t);return BigInt(t)}
export function assembleLine(line){const clean=line.replace(/;.*/,'').replace(/#.*/,'').trim();if(!clean)return null;const [mnemonic,...rest]=clean.replace(/,/g,' ').split(/\s+/);const opcode=byName[mnemonic.toUpperCase()];if(opcode===undefined)throw new SyntaxError(`unknown mnemonic ${mnemonic}`);const args=rest.filter(Boolean);const i={opcode,dst:0,srcA:0,srcB:0,immediate:0n};if(['NOT','MOV','SYS_CALL','BARRIER','POLICY_UPDATE'].includes(mnemonic.toUpperCase())){if(args[0]&&/^[RZ]\d+$/i.test(args[0]))i.dst=parseRegister(args[0]);if(args[1]&&/^[RZ]\d+$/i.test(args[1]))i.srcA=parseRegister(args[1]);else if(args[1])i.immediate=parseImmediate(args[1]);}else{if(args[0])i.dst=parseRegister(args[0]);if(args[1])i.srcA=parseRegister(args[1]);if(args[2]&&/^[RZ]\d+$/i.test(args[2]))i.srcB=parseRegister(args[2]);else if(args[2])i.immediate=parseImmediate(args[2]);}return i}
export function assemble(source,cpu){const lines=source.split(/\r?\n/).map(assembleLine).filter(Boolean);const c=cpu??new (awaitableCpu())();return Uint8Array.from(lines.flatMap(i=>Array.from(c.encode(i))))}
function awaitableCpu(){return class{encode(i){const b=new Uint8Array(16),d=new DataView(b.buffer);d.setUint16(0,i.opcode,true);d.setUint16(2,i.dst,true);d.setUint16(4,i.srcA,true);d.setUint16(6,i.srcB,true);let x=BigInt(i.immediate??0);for(let k=0;k<8;k++){b[8+k]=Number(x&255n);x>>=8n}return b}}}
export function disassembleInstruction(i){const name=isaCatalog.find(x=>x.opcode===i.opcode)?.name??`OP_${i.opcode.toString(16).padStart(4,'0')}`;return `${name} R${i.dst}, R${i.srcA}, R${i.srcB}${i.immediate?`, 0x${i.immediate.toString(16)}`:''}`}
export function isaJson(){return JSON.stringify({version:1,total:isaCatalog.length,instructions:isaCatalog},null,2)}
